import { type NextPage } from "next";
import Head from "next/head";
import ButtonAddTodo from "../components/ButtonAddTodo";
import ListItems from "../components/ListItems/ListItems";

import ApiContextProvider from "../context/ApiContext";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-row items-center justify-evenly gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            To Do App
          </h1>
          <ApiContextProvider>
            <div className="flex flex-col items-center justify-between ">
              <ButtonAddTodo/>
              <ListItems />
            </div>
          </ApiContextProvider>
        </div>
      </main>
    </>
  );
};

export default Home;
