import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { MouseEventHandler, useState } from "react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const {data: test, isLoading} = api.example.test.useQuery();


  const ButtonAddTodo = () => {
    const ctx = api.useContext();
    const {mutate} = api.example.createTest.useMutation({onSuccess: async () => {
       await ctx.example.invalidate();
  }})
    const [toDoName, setToDoName] = useState("");

    function handleAddTodo(){
      if(toDoName){
        mutate(toDoName)
      }
    }

    return (
      <div className="flex flex-row gap-2 ">
        <input type="text" onChange={(e) => setToDoName(e.target.value)} />
        <button className="text-white font-bold hover:text-[#2e026d] hover:bg-white rounded-lg p-2 border-2 border-white mr-2" onClick={handleAddTodo}>ADD</button>
      </div>
    )
  };

  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-row justify-evenly items-start gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            To Do App
          </h1>
          <div className="flex flex-col items-start justify-between gap-6 ">
          <ButtonAddTodo />
          <ul className="gap-2 flex flex-col w-full">
            {test?.map((el,i) => <li key={i} className="text-lg border-2 border-white p-2 text-white rounded-lg">{el}</li>)}
          </ul>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
